### ISSUE TITLE
unnecessary dependencies

### ISSUE THREAD

**Issue by sylvoslee** [stevej2608/dash-spa#2]

**Comment by sylvoslee** [comment]
Can you remove unnecessary dependencies in the installation package on pypi

**Comment by stevej2608** [comment]
Tidied up requirements.txt. v0.8.2 is on PyPi. 

Cheers, Steve

**Comment by sylvoslee** [comment]
Is libraries like pandas, SQLAlchemy necessary, and can a pure dash-spa be installed?

**Comment by stevej2608** [comment]
These are used by the admin blueprint. It could be split into it's own package (dash-spa-admin?). I don't have time to do it just now. If you want to do a PR I'd be happy to look at it.

**Comment by stevej2608** [comment]
Fixed. pip install dash-spa for minimal, no admin support.  pip install dash-spa[admin] to include admin
